### ISSUE TITLE
Failed to register tab Playlunky (wine)

### ISSUE THREAD

**Issue by The-ThirtyFour** [spelunky-fyi/modlunky2#261]
```
Failed to register tab Playlunky: Traceback (most recent call last):
  File "modlunky2\ui\__init__.py", line 429, in register_tab
  File "modlunky2\ui\play\play.py", line 137, in __init__
  File "modlunky2\ui\play\play.py", line 331, in on_load
  File "modlunky2\ui\play\packs.py", line 247, in on_load
  File "modlunky2\ui\play\packs.py", line 193, in get_packs
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
Failed to register tab Level Editor: Traceback (most recent call 
last):
  File "modlunky2\ui\__init__.py", line 429, in register_tab
  File "modlunky2\ui\levels\tab.py", line 107, in __init__
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
```

**Comment by mauvealerts** [comment]
The immediate cause of this bug is not having `install-dir` set in the config file. This case should be handled better, tho.

I suspect I broke this some time ago, but I'm having trouble figuring out how it behaved before my change.
