### ISSUE TITLE
Failed to load playlunky tab

### ISSUE THREAD

**Issue by lemonHeart45** [spelunky-fyi/modlunky2#438]
this is the thing it sent in console
2022-10-26 20:30:16,190: Failed to register tab Playlunky: Traceback (most recent call last):
  File "modlunky2\ui\__init__.py", line 429, in register_tab
  File "modlunky2\ui\play\play.py", line 141, in __init__
  File "modlunky2\ui\play\play.py", line 204, in load_from_load_order
  File "modlunky2\ui\play\play.py", line 246, in load_order_path
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
2022-10-26 20:30:16,213: Failed to register tab Level Editor: Traceback (most recent call last):
  File "modlunky2\ui\__init__.py", line 429, in register_tab
  File "modlunky2\ui\levels\tab.py", line 86, in __init__
TypeError: unsupported operand type(s) for /: 'NoneType' and 'str'
im new to github so if this isnt what this area is for then you can delete it or tell me

**Comment by lemonHeart45** [comment]
If there is anyway to fix it please tell me, yes i have already tried uninstalling and reinstalling, opening and closing.

**Comment by gmjosack** [comment]
Check that you have an install dir set in the settings tab.

**Comment by lemonHeart45** [comment]
> Check that you have an install dir set in the settings tab.

checking the settings tab i press install dir and nothing happens? should i click cache or data?

**Comment by lemonHeart45** [comment]
> Check that you have an install dir set in the settings tab.

thank you i feel dumb now lol

**Comment by mauvealerts** [comment]
No worries. The UI isn't great here
