### ISSUE TITLE
Playlunky tab is broken after update to 0.13.5.

### ISSUE THREAD

**Issue by Creta5164** [spelunky-fyi/modlunky2#72]
![image](https://user-images.githubusercontent.com/13521406/112935059-f72f7280-915d-11eb-83bb-27d706e7cd5b.png)

```log
2021-03-30 13:42:24,771: Failed to register tab Playlunky: Traceback (most recent call last):
  File "modlunky2\ui\__init__.py", line 218, in register_tab
  File "modlunky2\ui\play\__init__.py", line 833, in __init__
  File "modlunky2\ui\play\__init__.py", line 386, in render
  File "modlunky2\ui\play\__init__.py", line 344, in get_available_releases
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 4051: illegal multibyte sequence
```

**Comment by gmjosack** [comment]
It seems like the available releases file might have gotten corrupted somehow. Can you try removing

```
C:\Users\%USERNAME%\AppData\Local\spelunky.fyi\modlunky2\Cache\playlunky-releases.json
```

**Comment by Creta5164** [comment]
package JSON file dump : https://gist.github.com/Creta5164/68f05b9d988dce7d7abe1dc0ac6cc35f

I got different log after remove package file.

```log
2021-03-30 14:14:32,046: Unhandled Exception: Traceback (most recent call last):
  File "tkinter\__init__.py", line 1892, in __call__
  File "tkinter\__init__.py", line 814, in callit
  File "modlunky2\ui\__init__.py", line 186, in after_cb
  File "modlunky2\ui\tasks.py", line 181, in dispatch
  File "modlunky2\ui\play\__init__.py", line 439, in on_cache_releases_updated
  File "modlunky2\ui\play\__init__.py", line 386, in render
  File "modlunky2\ui\play\__init__.py", line 344, in get_available_releases
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 4051: illegal multibyte sequence
```

**Comment by gmjosack** [comment]
I just pushed a new update to attempt to read the file in utf-8 always. Can you update and test?

**Comment by Creta5164** [comment]
Okay, got it works fine 1.13.6, I'll close this issue!

**Comment by gmjosack** [comment]
Thanks for the detailed report and quick responses! I appreciate it :)

**Comment by TheMushroomKing211** [comment]
I'm having a similar issue and can't find how to fix it. a few days ago, i got Modlunky, and do0wnloaded a Skin mod for it. i haven't downloaded any other mods, and now it saying there uis a virus in one of the files, and won't let me use Modlunky. How do I fix this?
