### ISSUE TITLE
[0.28.2] Unicode decode failed byte 0xbe at position 226.

### ISSUE THREAD

**Issue by Creta5164** [spelunky-fyi/modlunky2#792]
Console log

```log
2023-06-05 22:44:56,656: Running on http://127.0.0.1:9526 (CTRL + C to quit)
2023-06-05 22:44:56,925: Failed to register tab Playlunky: Traceback (most recent call last):
  File "modlunky2\ui\__init__.py", line 436, in register_tab
  File "modlunky2\ui\play\play.py", line 149, in __init__
  File "modlunky2\ui\play\play.py", line 217, in load_from_load_order
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 226: invalid start byte
2023-06-05 22:44:58,736: Connected to spelunky.fyi
```

**Comment by gmjosack** [comment]
This should no longer happen in the release coming out soon.
